import type { Metadata } from 'next'
import { Geist } from 'next/font/google'
import './globals.css'
import Image from 'next/image'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Advanti',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased bg-primary-white`}>
        <div className='h-[88px] px-8 place-content-center'>
          <Image
          src={'/partners.svg'}
          alt='Advanti Logo'
          height={67}
          width={240}
          className='object-contain object-left max-h-[67.2px]'
          />
        </div>
        {children}</body>
    </html>
  )
}
